# Generated by Django 5.1.6 on 2025-02-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrativo', 'Administrativo'), ('administrador', 'Administrador'), ('repartidor', 'Repartidor'), ('cuadrilla', 'Cuadrilla')], default='cliente', max_length=20),
        ),
    ]
