# Generated by Django 5.1.6 on 2025-02-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuadrillas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacioncuadrilla',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.miembrocuadrilla'),
        ),
        migrations.AddField(
            model_name='asignacioncuadrilla',
            name='cuadrilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuadrillas.cuadrilla'),
        ),
    ]
